/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsCardRouteImport } from './routes/components/card'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsBadgeRouteImport } from './routes/components/badge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCardRoute = ComponentsCardRouteImport.update({
  id: '/components/card',
  path: '/components/card',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBadgeRoute = ComponentsBadgeRouteImport.update({
  id: '/components/badge',
  path: '/components/badge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/badge'
    | '/components/button'
    | '/components/card'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/components/badge' | '/components/button' | '/components/card'
  id:
    | '__root__'
    | '/'
    | '/components/badge'
    | '/components/button'
    | '/components/card'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsBadgeRoute: typeof ComponentsBadgeRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsCardRoute: typeof ComponentsCardRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/card': {
      id: '/components/card'
      path: '/components/card'
      fullPath: '/components/card'
      preLoaderRoute: typeof ComponentsCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button': {
      id: '/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/badge': {
      id: '/components/badge'
      path: '/components/badge'
      fullPath: '/components/badge'
      preLoaderRoute: typeof ComponentsBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsBadgeRoute: ComponentsBadgeRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsCardRoute: ComponentsCardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
