import path from 'node:path';
import { defineConfig } from 'vite';
import dts from 'vite-plugin-dts';
import solid from 'vite-plugin-solid';

export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
  build: {
    cssCodeSplit: true,
    lib: {
      entry: [
        'src/index.ts',
        'src/components/Accordion.tsx',
        'src/components/AlertDialog.tsx',
        'src/components/AspectRatio.tsx',
        'src/components/Avatar.tsx',
        'src/components/Badge.tsx',
        'src/components/Button.tsx',
        'src/components/Card.tsx',
        'src/components/Carousel.tsx',
        'src/components/Checkbox.tsx',
        'src/components/Collapsible.tsx',
        'src/components/Combobox.tsx',
        'src/components/Dialog.tsx',
        'src/components/Empty.tsx',
        'src/components/Field.tsx',
        'src/components/Input.tsx',
        'src/components/Item.tsx',
        'src/components/Kbd.tsx',
        'src/components/Label.tsx',
        'src/components/Link.tsx',
        'src/components/NavigationMenu.tsx',
        'src/components/NumberInput.tsx',
        'src/components/Pagination.tsx',
        'src/components/PasswordInput.tsx',
        'src/components/PinInput.tsx',
        'src/components/Popover.tsx',
        'src/components/Progress.tsx',
        'src/components/RadioGroup.tsx',
        'src/components/ScrollArea.tsx',
        'src/components/Select.tsx',
        'src/components/Separator.tsx',
        'src/components/Sheet.tsx',
        'src/components/sidebar/index.ts',
        'src/components/Skeleton.tsx',
        'src/components/Slider.tsx',
        'src/components/Spinner.tsx',
        'src/components/Switch.tsx',
        'src/components/Table.tsx',
        'src/components/Tabs.tsx',
        'src/components/TextInput.tsx',
        'src/components/Textarea.tsx',
        'src/components/Toaster.tsx',
        'src/components/Toggle.tsx',
        'src/components/Tooltip.tsx',
        'src/components/Typography.tsx',
        'src/theme.css',
      ],
      formats: ['es'],
    },
    rollupOptions: {
      external: [
        'solid-js',
        'solid-js/web',
        '@tanstack/solid-router',
        '@solid-primitives/i18n',
        '@ark-ui/solid/accordion',
        '@ark-ui/solid/toast',
        '@ark-ui/solid/tooltip',
        '@ark-ui/solid/switch',
        '@ark-ui/solid/popover',
        '@ark-ui/solid/progress',
        '@ark-ui/solid/slider',
        '@ark-ui/solid/radio-group',
        '@ark-ui/solid/dialog',
        'solid-icons/md',
        'tailwind-variants',
      ],
      output: {
        preserveModules: true,
        preserveModulesRoot: 'src',
      },
      treeshake: {
        moduleSideEffects: false,
      },
    },
    sourcemap: true,
  },
  plugins: [
    solid(),
    dts({
      entryRoot: 'src',
    }),
  ],
});
