/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Dynamic: typeof import('solid-js/web').Dynamic
  const ErrorBoundary: typeof import('solid-js').ErrorBoundary
  const For: typeof import('solid-js').For
  const IconIcBaselineCircle: typeof import('~icons/ic/baseline-circle').default
  const IconIcOutlineCalendarMonth: typeof import('~icons/ic/outline-calendar-month').default
  const IconIcOutlineCheck: typeof import('~icons/ic/outline-check').default
  const IconIcOutlineCheckCircle: typeof import('~icons/ic/outline-check-circle').default
  const IconIcOutlineChevronLeft: typeof import('~icons/ic/outline-chevron-left').default
  const IconIcOutlineChevronRight: typeof import('~icons/ic/outline-chevron-right').default
  const IconIcOutlineClose: typeof import('~icons/ic/outline-close').default
  const IconIcOutlineError: typeof import('~icons/ic/outline-error').default
  const IconIcOutlineExpandLess: typeof import('~icons/ic/outline-expand-less').default
  const IconIcOutlineExpandMore: typeof import('~icons/ic/outline-expand-more').default
  const IconIcOutlineInfo: typeof import('~icons/ic/outline-info').default
  const IconIcOutlineMoreHoriz: typeof import('~icons/ic/outline-more-horiz').default
  const IconIcOutlineRefresh: typeof import('~icons/ic/outline-refresh').default
  const IconIcOutlineRemove: typeof import('~icons/ic/outline-remove').default
  const IconIcOutlineUnfoldMore: typeof import('~icons/ic/outline-unfold-more').default
  const IconIcOutlineViewSidebar: typeof import('~icons/ic/outline-view-sidebar').default
  const IconIcOutlineVisibility: typeof import('~icons/ic/outline-visibility').default
  const IconIcOutlineVisibilityOff: typeof import('~icons/ic/outline-visibility-off').default
  const IconIcOutlineWarning: typeof import('~icons/ic/outline-warning').default
  const Index: typeof import('solid-js').Index
  const Match: typeof import('solid-js').Match
  const Portal: typeof import('solid-js/web').Portal
  const Show: typeof import('solid-js').Show
  const Suspense: typeof import('solid-js').Suspense
  const SuspenseList: typeof import('solid-js').SuspenseList
  const Switch: typeof import('solid-js').Switch
  const batch: typeof import('solid-js').batch
  const children: typeof import('solid-js').children
  const createContext: typeof import('solid-js').createContext
  const createDeferred: typeof import('solid-js').createDeferred
  const createEffect: typeof import('solid-js').createEffect
  const createMemo: typeof import('solid-js').createMemo
  const createMutable: typeof import('solid-js/store').createMutable
  const createRenderEffect: typeof import('solid-js').createRenderEffect
  const createResource: typeof import('solid-js').createResource
  const createRoot: typeof import('solid-js').createRoot
  const createSelector: typeof import('solid-js').createSelector
  const createSignal: typeof import('solid-js').createSignal
  const createStore: typeof import('solid-js/store').createStore
  const hydrate: typeof import('solid-js/web').hydrate
  const indexArray: typeof import('solid-js').indexArray
  const isServer: typeof import('solid-js/web').isServer
  const lazy: typeof import('solid-js').lazy
  const mapArray: typeof import('solid-js').mapArray
  const mergeProps: typeof import('solid-js').mergeProps
  const observable: typeof import('solid-js').observable
  const on: typeof import('solid-js').on
  const onCleanup: typeof import('solid-js').onCleanup
  const onError: typeof import('solid-js').onError
  const onMount: typeof import('solid-js').onMount
  const produce: typeof import('solid-js/store').produce
  const reconcile: typeof import('solid-js/store').reconcile
  const render: typeof import('solid-js/web').render
  const renderToStream: typeof import('solid-js/web').renderToStream
  const renderToString: typeof import('solid-js/web').renderToString
  const renderToStringAsync: typeof import('solid-js/web').renderToStringAsync
  const splitProps: typeof import('solid-js').splitProps
  const untrack: typeof import('solid-js').untrack
  const useContext: typeof import('solid-js').useContext
  const useTransition: typeof import('solid-js').useTransition
}
