name: CI

on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up Bun
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Debug oxfmt version
        run: bun x oxfmt --version
      - name: Build Library
        run: bun run build:lib
      - name: Build Docs
        run: bun run build:docs
      - name: Run oxlint
        run: bun run lint
      - name: Run formatting check
        run: bun run fmt:check
